const peopleEng = [
  {name:"Mr. G.",reason:"still hasn't started the minecraft server after all these days, so my resources are just gone forever now", level:2.5, hate:12},
  {name:"Yogurt",reason:"i just don't like this person, and i don't even know who this is",level:0.5, hate:8},
  {name:"Anastasia Shrew", reason:"no comment",level:5, hate:83},
  {name:"Amsalat",reason:"banned me and maxon, took oldie's mod, won't give back one dollar, and stole a role. asshole", level:3.5, hate:55},
  {name:"Nikich",reason:"made me download shitty assetto corsa just to play once, so i had to download a bunch of garbage. i don't like you", level:3, hate:21},
  {name:"Dedpi47",reason:"banned me on his fucking server. not that i wanted to be there that much, but still. i know you're reading this, and there'll be consequences", level:1, hate:35},
  {name:"Artyomka",reason:"just a piece of shit",level:5, hate:80},
  {name:"Sanek",reason:"keeps asking me to play cs while i'm asleep, then complains that i never play",  level:1, hate:3},
  {name:"Vazhdani",reason:"just annoys me, and also acts hostile toward me for some reason. i've seen your real face", level:3, hate:27},
  {name:"Miss V.",reason:"i had to add her here",level:5, hate:93},
  {name:"Rednek",reason:"banned me everywhere. i remember all of it, asshole",level:3.5, hate:50},
  {name:"Red Builder",reason:"has honestly gotten on my nerves already. i can't keep reading your bullshit",level:4, hate:78},
  {name:"Turbo",reason:"absolute piece of shit. banned me from the server and won't let me back in. sooner or later i'll be there again", level:5, hate:99},
  {name:"Dexter",reason:"said something nasty about me. that was all at first, but i knew there'd be more. update, he said more. then more again. he really doesn't stop", level:2.5, hate:18},
  {name:"Repevfrt",reason:"i've got no fucking idea who this is. they just called me on discord for some reason, so now they're on the list", level:1.5, hate:16},
  {name:"Mr. K.",reason:"just got on my nerves. a very unpleasant, exhausting, and awkward person",level:5, hate:95},
  {name:"Crash Bandicoot",reason:"called me son. disrespectful",level:1.5, hate:14},
  {name:"Logic",reason:"i just felt like putting him here. he didn't really do anything that bad, but yeah, he made it in", level:0.5, hate:9},
  {name:"Viplay",reason:"just a loser",level:3.5, hate:58},
  {name:"Mistgo",reason:"friend of a loser",level:3, hate:56},
  {name:"Rari",reason:"piece of shit, weird jerk, and all that. also called me abobus and argues all the time. apparently a person can't just live in peace without him adding his opinion. while writing this i got annoyed again, so that's one more point", level:3, hate:37},
  {name:"Darya",reason:"recommends shows and says they're the best thing she's ever watched, but then they turn out to be complete garbage. who's giving me those hours back? what the fuck is barry, who even watches that", level:2.5, hate:28},
  {name:"Dante",reason:"a loser and a shithead, very unpleasant overall. i wanted to give him a 5, but he gave me a forza account, and i remember good things too, so 3. plus another half because he showed off at me in chat",level:3.5, hate:67},
  {name:"B612",reason:"went to prison for terrorism for 20 years. what the fuck is that", level:2, hate:20},
  {name:"Hardonium",reason:"covered my minecraft house with sand. even if it was indirectly, this is still on him", level:1.5, hate:12},
  {name:"Chipi",reason:"muted me, then bragged to my friends, and then went to complain about us to his boyfriend",level:3.5, hate:76},
  {name:"F 16C Siberia Edition",reason:"caused the conflict that ended with oldie getting fired. awful person, traitor",level:3.5, hate:36},
  {name:"Mr. T.",reason:"sends tiktok memes on instagram. are you fucking serious",level:2, hate:21},
  {name:"Miss T.",reason:"her ideas, honestly",level:1.5, hate:1},
  {name:"Ayutta",reason:"wrote 'not fucking funny' under my joke. you're the one who's not fucking funny, just so we're clear",level:2.5, hate:45 },
  {name:"Kholodos",reason:"thief, fraud, war criminal, night racer. supplied kalashnikov rifles to conflict zones around the world, millions of people suffered because of him, and he's internationally wanted. also scammed investors by promising to build a huge combat robot. awful person",level: 1.5 , hate:13 },
  {name:"All Snails",reason:"i can't stand them",level:5, hate:100},
  {name:"Opossum Andrey",reason:"some old loser saying nasty things about me online. welcome to the list",level: 2, hate: 25},
  {name:"_Rayn_Gosling_",reason:"annoying boring loser",level: 3, hate: 26},
  {name:"Dima",reason:"i can't say the reason, but he annoys me so fucking much",level:4.5, hate:93},
  {name:"Memchik",reason:"mostly out of respect. peace to the fallen. he said nasty things to me too though",level:0.5, hate:12},
  {name:"Shendy",reason:"took over the server and now he's afraid to talk to us, so he just bans people",level:2, hate:43},
];
